customhost = "project-rdsdb1.chxnqectvvxw.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin123"
customdb = "project-rdsdb1"
custombucket = "project-s3bucket1"
customregion = "us-east-1"
